In [1]:
import numpy as np
import pandas as pd

In [2]:
irdf = pd.read_csv('MidExamSetSolutions/iris.csv')
irdf

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
irdf['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [4]:
x=irdf.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y=irdf.iloc[:,4].values
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
labelencoder_y= LabelEncoder()

In [8]:
y=labelencoder_y.fit_transform(y)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split 

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(f'x_train : ',x_train)
print(f'x_test : ',x_test)
print(f'y_train : ',y_train)
print(f'y_test : ',y_test)

x_train :  [[6.5 3.  5.2 2. ]
 [6.7 3.  5.2 2.3]
 [4.8 3.1 1.6 0.2]
 [5.6 3.  4.5 1.5]
 [5.6 2.7 4.2 1.3]
 [6.5 2.8 4.6 1.5]
 [6.7 3.3 5.7 2.1]
 [7.1 3.  5.9 2.1]
 [5.8 4.  1.2 0.2]
 [6.9 3.1 5.4 2.1]
 [5.4 3.  4.5 1.5]
 [4.8 3.4 1.6 0.2]
 [7.6 3.  6.6 2.1]
 [7.2 3.  5.8 1.6]
 [4.4 2.9 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [6.2 2.8 4.8 1.8]
 [5.4 3.7 1.5 0.2]
 [6.3 3.3 4.7 1.6]
 [6.3 3.4 5.6 2.4]
 [5.4 3.4 1.7 0.2]
 [6.9 3.1 4.9 1.5]
 [6.2 2.2 4.5 1.5]
 [6.  3.  4.8 1.8]
 [4.3 3.  1.1 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [5.6 2.8 4.9 2. ]
 [4.9 3.1 1.5 0.1]
 [5.2 4.1 1.5 0.1]
 [6.2 3.4 5.4 2.3]
 [6.3 2.9 5.6 1.8]
 [6.8 3.  5.5 2.1]
 [5.2 3.4 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [6.4 3.1 5.5 1.8]
 [5.7 2.8 4.1 1.3]
 [4.4 3.  1.3 0.2]
 [5.7 2.8 4.5 1.3]
 [4.8 3.4 1.9 0.2]
 [5.  3.2 1.2 0.2]
 [5.6 2.5 3.9 1.1]
 [4.7 3.2 1.3 0.2]
 [6.3 2.5 4.9 1.5]
 [6.2 2.9 4.3 1.3]
 [6.5 3.  5.8 2.2]
 [4.9 3.6 1.4 0.1]
 [6.7 3.1 4.7 1.5]
 [4.7 3.2 1.6 0.2]
 [5.5 4.2 1.4 0.2]
 

In [12]:
print(f'x_train shape : ',x_train.shape)
print(f'x_test shape : ',x_test.shape)
print(f'y_train shape : ',y_train.shape)
print(f'y_test shape : ',y_test.shape)

x_train shape :  (105, 4)
x_test shape :  (45, 4)
y_train shape :  (105,)
y_test shape :  (45,)


In [13]:
print(f'x_train size : ',x_train.size)
print(f'x_test size : ',x_test.size)
print(f'y_train size : ',y_train.size)
print(f'y_test size : ',y_test.size)

x_train size :  420
x_test size :  180
y_train size :  105
y_test size :  45


In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

/home/salogosm/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred= logmodel.predict(x_test)

In [17]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [18]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 15,  2],
       [ 0,  0, 14]])

In [21]:
(28/30)*100

93.33333333333333

In [22]:
logmodel.score(x_test,y_test)

0.9555555555555556