In [1]:
import numpy as np

In [2]:
arr1 = np.array([2,6,8,6,7,3])
arr1

array([2, 6, 8, 6, 7, 3])

In [3]:
arr1.size

6

In [4]:
arr1.shape

(6,)

In [5]:
arr1.dtype

dtype('int64')

In [6]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2.size

9

In [8]:
arr2.shape

(3, 3)

In [9]:
arr2.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr2.ndim

2

In [13]:
arr3 = np.array([[[1,1,2],[2,3,1]],[[54,6,2],[9,5,6]]])
arr3

array([[[ 1,  1,  2],
        [ 2,  3,  1]],

       [[54,  6,  2],
        [ 9,  5,  6]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.size

12

In [17]:
arr3.dtype

dtype('int64')

In [18]:
arr3.shape

(2, 2, 3)

In [19]:
zero1 = np.zeros(3)
zero1


array([0., 0., 0.])

In [22]:
zero2 = np.zeros((3,5))
zero2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zero3 = np.zeros((2,4,3))
zero3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
full1 = np.full(2,5)
full1

array([5, 5])

In [26]:
full2 = np.full((3,5),99)
full2

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [27]:
full3 = np.full((2,3,1),32)
full3

array([[[32],
        [32],
        [32]],

       [[32],
        [32],
        [32]]])

In [28]:
rand1 = np.random.rand(2,3)
rand1

array([[0.44376881, 0.95931155, 0.86079627],
       [0.41647064, 0.99830134, 0.74560375]])

In [29]:
rand2 = np.random.rand(3,2,2)
rand2

array([[[0.3230827 , 0.26508592],
        [0.55709134, 0.37164465]],

       [[0.81892614, 0.13519429],
        [0.06452233, 0.71000364]],

       [[0.21171782, 0.76424573],
        [0.56675879, 0.01803382]]])

In [30]:
one1 = np.ones(5)
one1

array([1., 1., 1., 1., 1.])

In [31]:
one2 = np.ones((3,2))
one2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
one3 = np.ones((5,3,4))
one3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
eye1 = np.eye(5)
eye1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
eye2 = np.eye(3)
eye2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
darr = np.array([2,56,6,45,1,0,-65])
darr

array([  2,  56,   6,  45,   1,   0, -65])

In [36]:
darr.sort

<function ndarray.sort>

In [37]:
darr.sort()

In [38]:
darr

array([-65,   0,   1,   2,   6,  45,  56])

In [39]:
darr2 = np.array([[3,2,4],[9,6,14]])
darr2

array([[ 3,  2,  4],
       [ 9,  6, 14]])

In [42]:
darr2.sort()
darr2

array([[ 2,  3,  4],
       [ 6,  9, 14]])

In [43]:
darr2.sort(axis=0)
darr2

array([[ 2,  3,  4],
       [ 6,  9, 14]])

In [44]:
darr2.sort(axis=1)
darr2

array([[ 2,  3,  4],
       [ 6,  9, 14]])

In [45]:
darr3 = np.array([[3,6,4551,0],[65,5,2,65]])
darr3

array([[   3,    6, 4551,    0],
       [  65,    5,    2,   65]])

In [46]:
darr3.sort(axis=1)

In [47]:
darr3

array([[   0,    3,    6, 4551],
       [   2,    5,   65,   65]])

In [48]:
darr3.shape

(2, 4)

In [50]:
darr3.reshape(4,2)

array([[   0,    3],
       [   6, 4551],
       [   2,    5],
       [  65,   65]])

In [51]:
np.delete(darr3,1,axis=1)
darr3

array([[   0,    3,    6, 4551],
       [   2,    5,   65,   65]])

In [52]:
d1 = np.delete(darr3,1,axis=1)
d1

array([[   0,    6, 4551],
       [   2,   65,   65]])

In [53]:
d1 = np.delete(darr3,1,axis=0)
d1

array([[   0,    3,    6, 4551]])

In [54]:
d1 = np.delete(darr3,2,axis=1)
d1

array([[   0,    3, 4551],
       [   2,    5,   65]])

In [56]:
d1 = np.delete(darr3,0,axis=0)
d1

array([[ 2,  5, 65, 65]])

In [57]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,8])
drarr = np.concatenate((arr1,arr2),axis=0)
drarr

array([1, 2, 3, 4, 5, 8])

In [62]:
arr1 = np.array([[1,2,3],[3,23,5]])
arr2 = np.array([[4,5,8],[51,5,2]])
drarr2 = np.concatenate((arr1,arr2),axis=1)
drarr2

array([[ 1,  2,  3,  4,  5,  8],
       [ 3, 23,  5, 51,  5,  2]])

In [64]:
new1 = np.split(drarr2,2)
new1

[array([[1, 2, 3, 4, 5, 8]]), array([[ 3, 23,  5, 51,  5,  2]])]

In [66]:
new1 = np.split(drarr2,2)
new1

[array([[1, 2, 3, 4, 5, 8]]), array([[ 3, 23,  5, 51,  5,  2]])]

In [67]:
dar1 = np.array([12,3,6])
dar1[2] = 100
dar1

array([ 12,   3, 100])

In [71]:
dar1[0:2]

array([12,  3])

In [72]:
dar2 = np.array([[1,2,3],[4,5,6]])
dar2[1][1]

5

In [73]:
dar2[0][2]=100
dar2

array([[  1,   2, 100],
       [  4,   5,   6]])

In [75]:
demo1 = np.array([[1,2,3],[4,5,6]])
demo2 = np.array([[1,2,3],[4,5,6]])
sumo = np.add(demo1,demo2)
sumo

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [77]:
subo = np.subtract(demo1,demo2)
subo

array([[0, 0, 0],
       [0, 0, 0]])

In [78]:
mulo = np.multiply(demo1,demo2)
mulo

array([[ 1,  4,  9],
       [16, 25, 36]])

In [79]:
divo = np.divide(demo1,demo2)
divo

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
demo1 = np.exp(demo1)
demo1

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [83]:
demo2 = np.sqrt(demo2)
demo2

array([[1.13314845, 1.28402542, 1.45499141],
       [1.64872127, 1.86824596, 2.11700002]])